import type { Metadata } from "next";
import "@/styles/global.css";
import AuthLayout from "@/components/layouts/auth/layout-auth";

export const metadata: Metadata = {
  title: "Management User",
  description: "Generated by create next app",
  icons: "logo/logo-hita-vidya-utama.png",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <AuthLayout>{children}</AuthLayout>
  );
}
