import type { Metadata } from "next";
import "@/styles/global.css"
import RootLayoutComponent from "@/components/layouts/root-layout";

export const metadata: Metadata = {
  title: "Management User",
  description: "Generated by create next app",
  icons: "logo/logo-hita-vidya-utama.png",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <div>
    <RootLayoutComponent>{children}</RootLayoutComponent>
  </div>;
}
