import type { Metadata } from "next";
import "@/styles/global.css";
import AdminLayout from "@/components/layouts/admin/layout-admin";

export const metadata: Metadata = {
  title: "Management User",
  description: "Generated by create next app",
  icons: "logo/logo-hita-vidya-utama.png",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <AdminLayout>{children}</AdminLayout>
  );
}
